[WIP] - Create and Delete Logical replication
IBM/cloud-databases-go-sdk pull request #9
Opened 2022-09-27 20:59 UTC by omaraibrahim

## PR summary

**Fixes:** <! -- link to issue -->

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type  

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## What is the current behavior?  

## What is the new behavior?  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

## Other information

2022-09-27 20:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/IBM/cloud-databases-go-sdk?pullRequest=9) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/IBM/cloud-databases-go-sdk?pullRequest=9) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/IBM/cloud-databases-go-sdk?pullRequest=9) it.</sub>

2022-10-10 14:58 UTC, alexhemard requested changes

2022-10-10 19:09 UTC, omaraibrahim commented on clouddatabasesv5/cloud_databases_v5_integration_test.go
> +			shouldSkipTest()
Done :D

2022-10-13 18:40 UTC, alexhemard requested changes

2022-10-13 18:40 UTC, alexhemard commented on clouddatabasesv5/cloud_databases_v5_integration_test.go
> +			}
This seems specific to testing Logical Replication slot. maybe move updating the `repl` user password into that test and leave this as-is

2022-10-13 18:40 UTC, alexhemard commented on clouddatabasesv5/cloud_databases_v5_integration_test.go
> +		if !strings.Contains(deploymentID, "postgresql") && !strings.Contains(deploymentID, "enterprisedb") {
`||` instead of `&&`  ?
```go
if strings.Contains(deploymentID,` "postgresql") || !strings.Contains(deploymentID, "enterprisedb")
```

2022-10-13 18:40 UTC, alexhemard commented on clouddatabasesv5/cloud_databases_v5_integration_test.go
> +			if strings.Contains(deploymentID, "postgresql") || strings.Contains(deploymentID, "enterprisedb") {
This test is already Postgresql specific and a `ConfigurationPgConfiguration` is already used before this. We should skip for PG or EnterpriseDB and address this in a different PR.

2022-10-17 17:35 UTC, closed without merging